resolver: nightly-2018-02-08

packages:
- '.'

extra-deps:
- conduit-1.3.0
- conduit-extra-1.3.0
- http-conduit-2.3.0
- yesod-core-1.6.1
- resourcet-1.2.0
- xml-conduit-1.8.0
- yesod-auth-1.6.1
- persistent-2.8.1
- yesod-form-1.6.1
- yesod-persistent-1.6.0
- ../yesod-fb
- ../fb


